apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: ip-tester
  name: ip-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ip-tester
  template:
    metadata:
      labels:
        component: ip-tester
    spec:
      containers:
        - image: docker.io/mfenwick100/kube-prototypes-ip-tester:latest
          imagePullPolicy: Always
          name: ip-tester
          command:
            - ./ip-tester
#          args:
#            - "server"
#            - "7890"
#          ports:
#            - containerPort: 7890
#              protocol: TCP
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 64Mi
              cpu: 100m
#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    component: ip-tester
#  name: ip-tester
#spec:
#  ports:
#    - port: 7890
#      name: port-7890
#  selector:
#    component: ip-tester
